config/manager/deployment.yaml

Remove namespace watch restriction, this allows Helm controller to act on HelmRelease at cluster level.

Watch for releases at cluster level

---

api/v2alpha1/helmrelease_types.go
config/crd/bases/helm.fluxcd.io_helmreleases.yaml
controllers/helmrelease_controller.go
docs/api/helmrelease.md
docs/spec/v2alpha1/helmreleases.md

This is the companion to 'Install.Replace' (and the only missing option flag).

Support KeepHistory flag for Helm uninstall action

---

controllers/helmrelease_controller.go

* Ensure Status.LastReleaseRevision is 0 after uninstall. This
could be nil instead, but since 0 is never a valid release revision,
it seems sufficient.
* Ensure uninstall leads to ready condition being false. This has
no effect now since uninstall is only triggered on install failure,
but will once other triggers (such as test failure) are supported.

Uninstall fixes

---

config/testdata/dependencies/helmrelease-backend.yaml
config/testdata/dependencies/helmrelease-frontend.yaml
config/testdata/dependencies/helmrepository.yaml
controllers/helmrelease_controller.go

Re-fix #31 
Before:
```
$ tk create hr sealed-secrets --interval=1h --release-name=sealed-secrets --target-namespace=gitops-system --source=stable --chart-name=sealed-secrets --chart-version="^1.10.0"
✚ generating release
► applying release
✔ release created
◎ waiting for reconciliation
✗ chart reconciliation failed: helmcharts.source.fluxcd.io "gitops-system-sealed-secrets" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```
After:
```
$ tk create hr sealed-secrets --interval=1h --release-name=sealed-secrets --target-namespace=gitops-system --source=stable --chart-name=sealed-secrets --chart-version="^1.10.0"
✚ generating release
► applying release
✔ release created
◎ waiting for reconciliation
✔ release sealed-secrets is ready
✔ applied revision …
```

Fix Helm chart update

---

api/v2alpha1/condition_types.go
api/v2alpha1/helmrelease_types.go
controllers/helmrelease_controller.go
docs/spec/v2alpha1/helmreleases.md

As "condition type names should describe the current observed state of
the resource, rather than describing the current state transitions".
(H/T @seaneagan https://github.com/fluxcd/toolkit/discussions/119#discussioncomment-40966)

Rename conditions to describe the current state

---

Makefile
config/rbac/role.yaml
controllers/helmrelease_controller.go

During high custom resource count / low interval tests, I was greated
with a `cannot patch resource "events"` message. This happened due to
event compaction, where it will perform a patch instead of a create.
By giving the role the permission to do so this should no longer pose
a problem.

Include PATCH rule for events in manager-role

---

Makefile

As it does not allow for error codes to surface.

Remove `find -execdir` from `Makefile`

---

.github/workflows/e2e.yaml
api/v2alpha1/condition_types.go
api/v2alpha1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
controllers/helmrelease_controller.go
docs/api/helmrelease.md
docs/spec/v2alpha1/helmreleases.md

Refactor status API
This removes:
- Installed, Upgraded, RolledBack, and Uninstalled status conditions
since they did not represent current state, but rather actions
taken, which are already recorded by events.
- status.observedStateReconciled since it solved the problem of
remembering past release (install/upgrade/test) success, but not
past release failures, after other subsequent failures such as
dependency failures, k8s API failures, etc.
This adds:
- Remediated status condition which records whether the release is
currently in a remediated state. It is used to prevent release retries
after remediation failures. We were previously not doing this for
rollback failures.
- Released status condition which records whether the current state
has been successfully released …

Refactor status API

---

api/v2alpha1/reference_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
controllers/helmrelease_controller.go
docs/api/helmrelease.md

This commit adds support for optional values references, as discussions
have brought to light that there are some valid use cases in which
having this option is desirable. For example to allow a user to extend
behaviour at a later date with their own repository without modifying
the HelmRelease object.
When a values reference is marked as optional, not found errors for the
value reference are ignored, but any ValuesKey, TargetPath or transient
error will still result in a reconciliation failure.
Ref: https://github.com/fluxcd/helm-controller/issues/42#issuecomment-693620588

Support optional values references

---

controllers/helmrelease_controller.go

We were logging the spec interval duration, which was incorrect:
1. On failures, which use exponential backoff
2. On dependency not ready, which uses a separately defined static interval.
This changes to log result.RequeueAfter directly when set.

Fix logging for next run delay

---

api/v2alpha1/condition_types.go
api/v2alpha1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
docs/api/helmrelease.md
docs/spec/README.md
docs/spec/v2alpha1/README.md
docs/spec/v2alpha1/helmreleases.md

This attempts to work towards the `extend documentation around managing Helm releases` task mentioned in https://github.com/fluxcd/toolkit/issues/238:
The thought here is to have a leveled documentation, increasing detail in each level, and avoiding too much duplication between levels:
1. https://toolkit.fluxcd.io/guides/helmreleases
2. https://toolkit.fluxcd.io/components/helm/helmreleases/
3. https://toolkit.fluxcd.io/components/helm/api/
This:
* copies some of the content about HelmRelease CRD options from 1. to 2. with the idea being to remove or reduce it from 1. and replace with a more prominent link to 2. (as a follow up in the toolkit repo).
* adds more documentation to 2.
* removes some of the copy/pasted golang documentation from 2. since it already exists in 3. The status …

Documentation improvements

---

controllers/helmrelease_controller.go

As the existing logic relied on other conditions that caused the
`released` to never be nil, but this may not be true for future
iterations, which makes this a case of better safe than sorry.

Prevent possible future nil pointer dereference

---

controllers/helmrelease_controller.go
controllers/helmrelease_controller_test.go
go.mod

As `ParseInto` expects the destination to be initialized, which led
to an `unable to parse key: assignment to entry in nil map` error in
configurations where the first `ValuesReference` had a `targetPath`
defined.
Fixes #113

Declare and assign result Values before composing

---

controllers/helmrelease_controller.go

As the watcher should trigger a reconciliation once the artifact
is available.

Do not requeue when chart is not ready

---

controllers/helmrelease_controller.go
controllers/source_predicate.go

The reason for this is the `EnqueueRequestsFromMapFunc` calling the
enqueuer for _both_ the old and the new object, and we only want to act
on the ones that contain a revision different from the one that we have
recorded in the status object of the `HelmRelease`.

Compare artifact <> HelmRelease in enqueuer

---

controllers/helmrelease_controller.go

Fixes #142 
* Requeue on chart and values composition errors to prevent a (temporary) dead lock on transient errors.
* Patch status sub-resource to resolve `the object has been modified; please apply your changes to the latest version and try again` errors and maintain better observed state.
Much of this was discovered in #127, and already applied to other controllers.

Patch status sub-resource and requeue on some errors

---

controllers/helmrelease_controller.go

In case the artifact watcher doesn't receive the chart update event, we should requeue based on the specfied interval to avoid a forever stuck HelmRelease.
Fix: #153

Requeue after interval on source not found errors

---

api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
controllers/helmrelease_controller.go

If a resource is marked as suspended we should not perform any
reconciliation action for the resource at all.
This includes updating the status of the resource to a
`Ready==False` state, as this is not an accurate representation of
the resource's state: we have been told to no longer look at it
and with that our last observation freezes in time.
Resource deletions are the sole exception to actions (not) being
performed, as we are duty-bound to remove our finalizer from the
resource to make a deletion succeed.
To make the suspend state still visible to the user, a column has
been added to the Custom Resource Definition which prints the
`.spec.suspend` of every HelmRelease.
```
❯ kubectl get helmrelease
NAME          READY   STATUS                             SUSPENDED   AGE
podinfo …
```

Do not mark suspended resource as not ready

---

api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml

As setting it in-cluster without commiting will otherwise result
in drift and overwrite attempts.
Given that without it the "suspended" column would show empty
fields when they are "false", this column has been removed.
Signed-off-by: Hidde Beydals <hello@hidde.co>

Remove default value from suspend field

---

.github/workflows/e2e.yaml
api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
config/testdata/install-create-target-ns/helmrelease.yaml
docs/api/helmrelease.md
docs/spec/v2beta1/helmreleases.md
internal/runner/runner.go

This adds support for creating the target release namespace if it is not
present which can be be useful in certain scenarios.
Note that when the release is uninstalled, the namespace is not removed
and remains on the cluster, and managing your namespace _outside_ of
the HelmRelease is advised.
Fixes: #130

Support Helm's NS creation for TargetNamespace

---

MAINTAINERS

See https://github.com/fluxcd/flux2/discussions/515.
@seaneagan Since you may not have seen the discussion above: this change is mainly for streamlining the maintenance of permissions and MAINTAINERS files, and not as a governance change. You can push back, if you do not wish this project to import maintainers from fluxcd/flux2.

Share flux2 maintainers

---

go.mod
go.sum

Replace mergo version used by controller-runtime which is broken [0],
until we can move to controller-runtime 0.7.0 which no longer uses this version.
Fixes #152
[0]: https://github.com/imdario/mergo/issues/139

Replace broken mergo version

---

config/manager/deployment.yaml

To a total of 10 minutes (600s), this allows most release process that
just have been started and make use of the default timeouts to finish.
In a future release, we will likely want to be able to stop a
reconciliation process between the reconciliation steps and continue on
the pod restart (e.g. upgrade -> terminate -> start -> continue with
test).
Helps addressing #149

Increase default `terminationGracePeriodSeconds` to `600`

---

go.mod

As of #183 this is no longer needed.

Remove mergo version replacement

---

CONTRIBUTING.md
controllers/helmrelease_controller_chart.go

This PR makes it possible to run helm-controller locally for debugging purposes against a test cluster.

Allow the controller to be run locally

---

controllers/helmrelease_controller.go

At the moment, you are not sure if the release has started and you have to wait for events showing its success or failure, or watch the status of k8s resources.
This adds an event notifying us that a release has started, we have found this to be especially useful for our slack messages in our deployment channels.

add a release deployment event when reconciling a release

---

controllers/helmrelease_controller.go
go.mod
go.sum
internal/util/util.go
internal/util/util_test.go

pkg/runtime v0.8.2 introduces runtime/transform which includes `MergeMaps`: https://github.com/fluxcd/pkg/pull/85

Use `MergeMaps` from pkg/runtime v0.8.2

---

controllers/helmrelease_controller.go
controllers/helmrelease_controller_chart.go
go.mod
main.go

This PR implements retries with exponential backoff when fetching artifacts from source-controller. By default, the controller does 10 attempts within a 3.5 minutes window, the number of max retries can be configure using the `--http-retry` cmd arg.
This mitigates the alert spam (`i/o timeout err`) when source-controller becomes unavailable for a short period of time e.g. after an upgrade. 
Ref: https://github.com/fluxcd/flux2/discussions/661 https://github.com/fluxcd/notification-controller/issues/76

Retry with exponential backoff when fetching artifacts

---

controllers/helmrelease_controller.go

Before:
```
{"level":"info","ts":"2021-03-03T12:45:41.305Z","logger":"controller.helmrelease","msg":"could not find optional %s '%s'","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"cert-manager","namespace":"kommander","ConfigMap":{"namespace":"kommander","name":"cert-manager-overrides"}}
```
After:
```
{"level":"info","ts":"2021-03-03T13:56:46.365+0100","logger":"controller.helmrelease","msg":"could not find optional ConfigMap 'kommander/cert-manager-overrides'","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"cert-manager","namespace":"kommander"}
```

fix: log messages contain '%s'

---

controllers/helmrelease_controller.go

Part of [flux#590](https://github.com/fluxcd/flux2/issues/590)
Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>

Record suspend metrics

---

api/go.mod
api/go.sum
controllers/helmrelease_controller.go
go.mod
go.sum

Part of [flux#590](https://github.com/fluxcd/flux2/issues/590)
Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>

Record suspension metrics

---

internal/runner/post_renderer_origin_labels.go
internal/runner/post_renderer_origin_labels_test.go
internal/runner/runner.go

This commit adds a new post renderer that labels all resources with
`helm.toolkit.fluxcd.io/name` and `helm.toolkit.fluxcd.io/namespace`
so their source of origin can be traced back by e.g. the Flux UI.
The post renderer makes use of the Kustomize API without running
a full Kustomize build, by making directly use of the builtin
`LabelTransformerPlugin` on a `ResMap` that has been constructed
from the bytes of the `bytes.Buffer` given by Helm.

Label release resources with HelmRelease origin

---

api/go.mod
api/go.sum
go.mod
go.sum
main.go

This PR allows fine tuning the leader election with cmd args:
```
--enable-leader-election=true
--leader-election-release-on-cancel=true
--leader-election-lease-duration=35s
--leader-election-renew-deadline=30s
--leader-election-retry-period=5s
```
To make the leader election more tolerant to transient Kubernetes API outages, the renewal deadline was increased from 10s to 30s and the retry interval was bumped to 5 seconds.
Test image:
```
docker.io/stefanprodan/helm-controller:le-config-b74081d
```
Part of: https://github.com/fluxcd/pkg/issues/94

Set leader election deadline to 30s

---

controllers/helmrelease_controller.go
internal/runner/log_buffer.go
internal/runner/log_buffer_test.go
internal/runner/runner.go

Capture and expose debug (log) information on release failure

---

.github/workflows/e2e.yaml
api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
config/testdata/charts/crds/bootstrap/.helmignore
config/testdata/charts/crds/bootstrap/Chart.yaml
config/testdata/charts/crds/bootstrap/templates/git-repository.yaml
config/testdata/charts/crds/bootstrap/values.yaml
config/testdata/charts/crds/v1/.helmignore
config/testdata/charts/crds/v1/Chart.yaml
config/testdata/charts/crds/v1/crds/a.yaml
config/testdata/charts/crds/v1/crds/b.yaml
config/testdata/charts/crds/v1/crds/d.yaml
config/testdata/charts/crds/v1/templates/dummy.yaml
config/testdata/charts/crds/v2/.helmignore
config/testdata/charts/crds/v2/Chart.yaml
config/testdata/charts/crds/v2/crds/a.yaml
config/testdata/charts/crds/v2/crds/b.yaml
config/testdata/charts/crds/v2/crds/c.yaml
config/testdata/charts/crds/v2/templates/dummy.yaml
config/testdata/charts/crds/v2/values.yaml
config/testdata/crds-upgrade/create-replace/helmrelease.yaml
config/testdata/crds-upgrade/create/helmrelease.yaml
config/testdata/crds-upgrade/init/helmrelease.yaml
docs/api/helmrelease.md
docs/spec/v2beta1/helmreleases.md
internal/runner/runner.go

This PR adds preliminary support for Upgrading CRDs which are part of Helm Charts managed via `HelmRelease` objects.
See also https://github.com/fluxcd/flux2/discussions/1071 for more information.
Helm still does not provide any built-in solution to the CRD upgrade problem, which is well-known and
[documented](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/):
> There is no support at this time for upgrading or deleting CRDs using Helm. This was an explicit decision after much community discussion due to the danger for unintentional data loss. Furthermore, there is currently no community consensus around how to handle CRDs and their lifecycle. As this evolves, Helm will add support for those use cases.
This limitation of Helm makes GitOps style "day 2 operations" of …

Initial support for HelmRelease for upgrading CRDs

---

docs/spec/v2beta1/helmreleases.md

should be `spec.install.createNamespace`

docs: minor `createNamespace` placement fix

---

internal/runner/log_buffer.go
internal/runner/runner.go

Changed in a6cc150aa6e4ec5c7613616f8ce194f9ae2f6e04 without a clear
reason, may be restored in the future but this depends on
[`a6cc150` (#250)](https://github.com/fluxcd/helm-controller/pull/250/commits/a6cc150aa6e4ec5c7613616f8ce194f9ae2f6e04#r617706942)

Restore log buffer size to 5

---

internal/runner/runner.go

This gives the in the previous MINOR release introduced CRD policy
precedence, avoiding `skipCRDs is set to false and crds is set to
Skip` errors when the `skipCRDs` field is omitted.
Fixes #260
Follow up #250

Give CRD policy precedence over skipCRDs field

---

docs/spec/v2beta1/helmreleases.md

The spec docs differs from the api docs, missing the information about ValuesFiles. This also is not shown in https://fluxcd.io/docs/components/helm/helmreleases/#specification that I guess comes from this file and why I realized it was no there. I'm not sure if there is an automation for this file or not but did not find it, I saw one for the api doc one.
Signed-off-by: Filinto Duran <duranto@gmail.com>

Fix HelmChartTemplateSpec Doc missing valuesFiles info

---

api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
docs/api/helmrelease.md
docs/spec/v2beta1/helmreleases.md
internal/runner/runner.go

Adding support for setting wait-for-jobs in HelmRelease.
https://github.com/helm/helm/issues/5948

Add support for Helm `--wait-for-jobs` flag

---

config/default/kustomization.yaml
go.mod
go.sum

- Helm to v3.6.1
- source-controller to v0.15.1
Helm's release is a security update but does not have an impact on the
helm-controller as all transport is handled by the source-controller.

Update Helm and source-controller

---

controllers/helmrelease_controller.go
controllers/helmrelease_controller_test.go

When the values contain quoted strings, use ParseIntoString to enforce they are set as strings.
This allows a similar behavior with CLI --set-string.

Treat quoted values as string when targetPath is set

---

controllers/helmrelease_controller.go
internal/util/util.go

Replace old utility function ObjectKey with controller-runtime's
client.ObjectKeyFromObject.

Remove old util ObjectKey

---

controllers/helmrelease_controller.go
docs/spec/v2beta1/helmreleases.md

Add `values.yaml` to the supported kubeconfig secret key names in order for SOPS to correctly detect the storage format based on the file extension.
Ref: https://github.com/fluxcd/kustomize-controller/pull/400

Make the kubeconfig secrets compatible with SOPS

---

.github/workflows/e2e.yaml
api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
config/testdata/status-defaults/helmrelease.yaml

This resolves an issue with kustomize-controller marking a
Kustomization as healthy even when the helm-controller hasn't even
looked at the HelmRelease targeted by the Kustomization's
healthChecks, yet. Setting `observedGeneration` to -1 by default will
cause kstatus to report a status of `InProgress` instead of `Ready`.
see https://github.com/fluxcd/kustomize-controller/issues/387 for
details on the issues this is solving.
Signed-off-by: Max Jonas Werner <mail@makk.es>

feat: set default observedGeneration to -1 on HelmReleases

---

docs/spec/v2beta1/helmreleases.md

Having used the indentation from the example, `images` and `patchesJson6902` are under `kustomize`. That resulted in the error:
```
validation failed: error: error validating "10f75846-394d-40a5-9fa1-73cd189b8703.yaml": error validating data: ValidationError(HelmRelease.spec.postRenderers[0]): unknown field "images" in io.fluxcd.toolkit.helm.v2beta1.HelmRelease.spec.postRenderers; if you choose to ignore these errors, turn validation off with --validate=false
```
Having shifted `images` as a field of `kustomize` seems to have worked.

Fix indentation for PostRenderers example

---

go.mod
go.sum

- https://github.com/advisories/GHSA-c2h3-6mxw-7mvq
- https://github.com/advisories/GHSA-c72p-9xmj-rx3w

Replace containerd with version that patches CVEs

---

config/default/kustomization.yaml
controllers/helmrelease_controller_chart.go
go.mod
go.sum

After downloading an artifact, compute its checksum and verify that it matches the original checksum as advertised by source-controller.
For backwards compatibility with source-controller v0.17.2, the checksum is computed with SHA1, on clusters with a newer source-controller we use SHA256.
Addresses https://github.com/fluxcd/source-controller/issues/468

Verify artifacts integrity

---

go.mod
go.sum

Another patch for CVE-2021-41190. Missed this one in #361.

Update opencontainers/image-spec to v1.0.2

---

.gitignore
Makefile

If we download the project in a local environment with no `kubebuilder` and `kubebuilder-tools`, or with an outdated version of `controller-gen`, executing `make test` will fail (see also [this comment](https://github.com/fluxcd/helm-controller/issues/341#issuecomment-981760932)).
This PR copies the approach of latest version of `kubebuilder`, downloading the executables in a local directory and consuming them from there.
(since apparently [there's no release for envtest](https://github.com/kubernetes-sigs/controller-runtime/issues/1670), I had to use `latest`)
Signed-off-by: Cecilia Bernardi <cbernardi@expediagroup.com>

Download and use controller-gen and envtest locally

---

controllers/helmrelease_controller.go

Changes summary:
- Add check for nil to fix inconsistent code-style raised at the security audit.
- Short-circuit function when `ExternalEventRecorder` is nil.
Relates to https://github.com/fluxcd/pkg/issues/173

Fix inconsistent code-style raised at security audit

---

Dockerfile
config/manager/deployment.yaml
go.mod

Further restricts the `SecurityContext` that the controller runs under, by enabling the default seccomp profile, dropping all linux capabilities. 
This was set at container-level to ensure backwards compatibility with use cases in which more privileged sidecars are injected into the `source-controller` pod without setting less restrictive settings.
Note that seccomp will only be enabled if the container runtime and operational system supports it, otherwise the container will run `unconfined` (aka fail-open), which is the same behaviour as not setting the `seccompProfile` in the first place.
Relates to https://github.com/fluxcd/flux2/issues/2014
Co authored by @aryan9600
Impacts https://github.com/weaveworks/flux2-openshift/issues/10
BREAKING CHANGE: 
- The use of new seccomp API requires …

security: Drop capabilities, set userid and enable seccomp

---

controllers/helmrelease_controller.go
controllers/helmrelease_controller_chart.go
controllers/helmrelease_controller_chart_test.go
docs/spec/v2beta1/helmreleases.md
go.mod
go.sum
main.go

Introduce the flag `--no-cross-namespace-refs` (defaults to false) for allowing cluster admins to disable cross-namespace references to sources.
When the controller is run with `--no-cross-namespace-refs=true` and `chart.spec.sourceRef` refers to a `GitRepository`, `Bucket` or `HelmRepository` in a different namespace than the `HelmRelease` object, the reconciliation will fail with the `AccessDenied` reason.
On access denied errors the controller logs and sends an event e.g.:
```
can't access 'GitRepository/my-other-namespace/my-source', cross-namespace references have been blocked
```
And the `HelmRelease` status `Ready` condition it set to:
```yaml
status:
conditions:
- lastTransitionTime: "2022-01-26T07:26:48Z"
message: "can't access 'GitRepository/my-other-namespace/my-source', …
```

Allow disabling cross-namespace references

---

controllers/helmrelease_controller.go
docs/spec/v2beta1/helmreleases.md
go.mod
go.sum
internal/kube/client.go
main.go

Introduce the flag `--default-service-account` for allowing cluster admins to enforce impersonation across the cluster without having to use an admission controller. 
When the flag is set to a value that's not empty string, all HelmReleases which don't have `spec.serviceAccountName` specified will use the service account name provided by `--default-service-account=<SA Name>` in the namespace of the object.
**Breaking changes**: 
- When `--default-service-account=<SA name>` and/or `spec.ServiceAccountName` are specified, the controller no longer queries the API to extract and use the SA token. Instead, the controller relies on the Kubernetes impersonation feature to run the reconciliation under the `system:serviceaccount:<SA Namespace>:<SA Name>` identity. This impacts only clusters with …

Allow setting a default service account for impersonation

---

tests/fuzz/fuzz_controllers.go

oss-fuzz integration breaks as some of the execution modes merges with test code leading to duplicated symbols.

Rename fuzzScheme to fix fuzz integration

---

api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
docs/api/helmrelease.md
docs/spec/v2beta1/helmreleases.md
internal/runner/runner.go

Add a uninstall `disableWait` property on Helm Release Uninstall API, so users can set whether Helm Controller waits for all the  resources to be deleted before finalizing the Helm Release.
This is very handy to ensure Helm Releases are fully un-installed. See [Slack Thread](https://cloud-native.slack.com/archives/CLAJ40HV3/p1644503412939859).

Add uninstall disableWait flag

---

api/go.mod
api/go.sum
controllers/helmrelease_controller.go
go.mod
go.sum
internal/kube/client.go

We don't map the client QPS and Burst setting resulting in client-side throttling when impersonating, making the kube-prom-stack upgrade take 25 minutes instead of one minute.

Set QPS and Burst when impersonating service account

---

api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml

Status content could be very long compare to other fields. Moving it to
the end helps improve the visibility of other fields.
Ref: https://github.com/fluxcd/flux2/issues/2385

api: Move Status in CRD printcolumn to the end

---

config/manager/deployment.yaml

Ref: https://github.com/fluxcd/flux2/issues/2537
In https://github.com/fluxcd/source-controller/issues/284#issuecomment-774703153 it seems that leaving fsGroup unset can result in this error.

add fsgroup for securityContext

---

go.mod
go.sum
tests/fuzz/go.mod

This mitigates CVE-2022-23648.

Update {containerd: v1.5.10, kustomize: v4.5.2} and tidy go.mod

---

api/v2beta1/helmrelease_types.go

Follow up on #421 to fully implement new tooling requirements. By
implementing the interfaces, the `conditions` package can now be used.

Implement `meta.ObjectWithConditions` interfaces

---

Makefile
controllers/helmrelease_controller.go
go.mod
go.sum
internal/kube/client.go
main.go

Two new flags were added to allow users to enable the use of user.Exec (`--insecure-kubeconfig-exec`) and InsecureTLS (`insecure-kubeconfig-tls`) in the kubeconfigs provided for remote apply.
Breaking change: both functionalities are no longer enabled by default.
Provides feature parity with `kustomize`: https://github.com/fluxcd/kustomize-controller/pull/593

Add kubeconfig flags

---

controllers/helmrelease_controller.go
main.go

As per other controllers, this adds two new flags that allow users to configure the exponential back-off for objects.
This resolves #463

Add flags for exponential back-off retry

---

api/go.mod
api/go.sum
api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
controllers/helmrelease_controller.go
docs/api/helmrelease.md
go.mod
go.sum

Support defining a KubeConfig Secret data key

---

controllers/helmrelease_controller.go

Follow up on #461 to align with changes suggested during review in https://github.com/fluxcd/kustomize-controller/pull/615.

kubeconfig: err on missing declared SecretRef.Key

---

docs/spec/v2beta1/helmreleases.md

spec: take note of KubeConfig.SecretRef.Key field

---

controllers/helmrelease_controller.go
go.mod
internal/kube/builder.go
internal/kube/builder_test.go
internal/kube/client.go
internal/kube/client_test.go
internal/kube/config.go
internal/kube/config_test.go
internal/kube/impersonate.go
internal/kube/impersonate_test.go
main.go

4371610e4ba2b07e1e0c5641d1145ca3fb34ee07 is a partial cherry-pick of commit ae4f499, including
changes around `kube`. This to include some of the changes around the
construction of the ConfigFlags RESTClientGetter, as an attempt to
solve token refresh issues.
As icing on the cake, 93bd5ed64fd59a9f2078e32d5b29808ca3ba1a4a always retrieves the current token from the FS which fixes #479 and https://github.com/fluxcd/flux2/issues/2074.

kube: load KubeConfig (token) from FS on every reconcile

---

docs/spec/v2beta1/helmreleases.md

Fixes #478 
Signed-off-by: sbernheim <1707604+sbernheim@users.noreply.github.com>

Updating API group name to helm.toolkit.fluxcd.io in docs

---

controllers/helmrelease_controller.go
internal/kube/builder.go
internal/kube/builder_test.go
internal/kube/client.go
internal/kube/client_test.go

Fixing a regression introduced in #480 which would always pick the
namespace of the release. In addition, historically seen the
configuration of the impersonation username while making use of a
KubeConfig has never worked correctly, this has been adressed as well.

kube: configure proper account impersonation NS

---

go.mod
go.sum

This addresses CVE-2022-1996, due to v2.16.0 including emicklei/go-restful@9266625.

Fix github.com/emicklei/go-restful (CVE-2022-1996)

---

api/v2beta1/reference_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
controllers/helmrelease_controller_test.go
controllers/suite_test.go
docs/api/helmrelease.md
go.mod
go.sum

Formalises the API requirements around TargetPath and ValuesKey,
which were the two fields missing validation within ValuesReference.
In both cases the validation was introduced at CRD level, so that
the apiserver will enforce it. 
ValuesKey must be a valid Data Key. Therefore the same logic used by
upstream Kubernetes is reused here to ensure a valid key is being used.
For TargetPath a loose regex is being used to largely represent the
expected format. A max length of 250 is now being enforced.
This is a breaking change, as invalid TargetPath and ValuesKey will now
be rejected by the apiserver, instead of being accepted and potentially
failing at reconciliation time.

Add validation to TargetPath and ValuesKey

---

api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml

To solve discrepancies between parsing versus validation.
xref: https://github.com/kubernetes/apimachinery/issues/131

api: add custom validation for v1.Duration types

---

.github/workflows/cifuzz.yaml
.github/workflows/e2e.yaml
.github/workflows/scan.yaml
Dockerfile
Makefile
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
config/rbac/role.yaml

Changes:
- Update Go to 1.19 in CI
- Use Go 1.19 in base image
- Update controller-gen v0.8.0 (v0.7 fails with Go 1.19) and regenerate manifests

Build with Go 1.19

---

api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml

Signed-off-by: Zhongcheng Lao <Zhongcheng.Lao@microsoft.com>
This addresses the issue that 'h' may produce a validation error when updating `HelmRelease` resource.

Allow 'h' in HelmRelease timeout field

---

main.go

Overriding the default GracefulShutdownTimeout option given to the controller manager with a default of 0 (no timeout) since the helm operations are sensitive to interruption and can lead to leaving the HelmRelease in a bad state.
This will also allow users to override the option via a CLI flag `-graceful-shutdown-timeout` how much time to wait before forcibly exiting.

Allow overriding ctrl manager graceful shutdown timeout

---

internal/features/features.go
main.go

Fixes #512 .
By default, `controller-runtime` gives you a cache-backed client, which will perform a LIST operation on any API type that you fetch, even if you use a GET request like we do: https://github.com/fluxcd/helm-controller/blob/5a7d0f8535406d155ed7d0634b27574538febed0/controllers/helmrelease_controller.go#L556
So unless you restrict helm-controller to a specific namespace with `--watch-all-namespaces=false`, then it will attempt to populate its cache by listing all secrets in the cluster, even if it only needs to access a few in specific namespaces. That requires giving helm-controller the ability to read every secret in the cluster.
This PR allows users to avoid that restriction by disabling caching of secrets. Now users can deploy HelmReleases that use `valuesFrom` without …

Disable caching of secrets and configmaps

---

.github/workflows/e2e.yaml
main.go

Setting the default value for the graceful-shutdown-timeout flag to match the default terminationGracePeriodSeconds value we set for the controller pod container.
It seems the controller-runtime does not support passing -1 as a value to skip the timeout as documented here:
https://github.com/kubernetes-sigs/controller-runtime/blob/v0.13.1/pkg/manager/manager.go#L286
With this change, it would also make sense to update the documentation to add a new section about graceful shutdown and explain the relation between these two values and also related to how the readiness probe affects graceful shutdown.

Align graceful-shutdown-timeout with terminationGracePeriodSeconds

---

.github/workflows/e2e.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yml
Dockerfile

Ref: https://github.com/fluxcd/flux2/issues/3522

build: Enable SBOM and SLSA Provenance

---

internal/features/features.go
internal/runner/runner.go

This allows install and upgrade actions to use DNS lookups while rendering Helm templates after it got disabled in Helm due to possible security risks.
It is enabled (globally) on the controller by configuring `--feature-gates=AllowDNSLookups=true`.
Fixes: #618

helm: enable DNS with AllowDNSLookups feature gate

---

internal/runner/log_buffer.go
internal/runner/log_buffer_test.go
internal/runner/runner.go

This reduces the amount of log lines pushed to `debug` by configuring the kube client and storage loggers to only log to `trace`.
In addition, the log buffer used in events will now just contain the most relevant information about a failure as reported by the Helm action itself, and not the in-depth information from the underlying client and/or storage.

runner: configure Helm action cfg log levels

---

.github/workflows/e2e.yaml
config/testdata/delete-ns/test.yaml
controllers/helmrelease_controller.go

Check if the service account to be impersonated actually exists
and proceed with uninstalling the Helm release only if it does.
Otherwise, skip uninstalling the release and carry on with finalization.
Add an e2e test to check if deleting a namespace with the RBAC and
HelmRelease succeeds with the namespace being fully deleted.

check if service account exists before uninstalling release

---

internal/features/features.go
internal/oomwatch/watch.go
internal/oomwatch/watch_test.go
main.go

This PR introduces an OOM watcher, which can be enabled using
`--feature-gates=OOMWatch=true`. The OOM watcher watches the current
memory usage as reported by cgroups via `memory.current` and cancels
the context when it reaches a certain threshold compared to
`memory.max` (default `95`%, configurable using
`--oom-watch-memory-threshold`).
This allows ongoing Helm processes to gracefully exit with a failure
before the controller is forcefully OOM killed, preventing a deadlock
of releases in a pending state.
The OOM watcher polls the `memory.current` file on an interval (default
`500ms`, configurable using `--oom-watch-interval`), as subscribing to
file updates using inotify is not possible for cgroups (v2) except for
`*.events` files. Which does provide signals using `memory.events`, but …

Introduce OOM watcher to allow graceful shutdown

---

internal/oomwatch/watch.go
internal/oomwatch/watch_test.go
main.go

This PR adds support for recognizing cgroup v1 paths, and allows for the configuration of alternative absolute path locations using `--oom-watch-max-memory-path` and `--oom-watch-current-memory-path`.
Fixes #640

oomwatch: auto detect well known cgroup paths

---

controllers/helmrelease_controller.go
controllers/helmrelease_controller_chart.go
go.mod
go.sum

This commit changes the verification to the `Digest` field of the Artifact, which was introduced in source-controller v0.35.0. As the `Checksum` is expected to be removed in the next release of the source-controller.

Verify Digest of Artifact

---

api/v2beta1/helmrelease_types.go
go.mod
internal/controllers/helmrelease_controller.go
internal/util/util.go
internal/util/util_test.go

Fixing this issue https://github.com/fluxcd/helm-controller/issues/675
Helm upgrade always happens without any changes
Clone from #676

Stable sort release values by key

---

internal/controller/helmrelease_controller.go

Likely after the upgrade to controller-runtime v0.15.0 a regression surfaced for long-running reconciliations of HelmRelease resources (e.g. for charts having pre-upgrade hooks taking a few minutes to complete). This regression would cause the controller to immediately re-run the upgrade after a successful upgrade, thus entering an almost-endless loop.
Apparently, the only fix to this issue is to ensure `.Status.LastReleaseRevision` is updated as soon as possible in the reconiliation cycle rather than wait for the update at the end of the cycle.

Fix HelmRelease reconciliation loop

---

.github/workflows/backport.yaml

This allows GitHub Action workflows to be triggered for the PR created by the bot.
As things are now triggered by the bot, elevated permissions of the workflow itself are no longer required.

ci: use bot token for backport

---

Makefile
docs/api/v2beta1/helm.md
docs/spec/v2beta1/helmreleases.md
hack/api-docs/template/pkg.tpl

In some controller we already support multiple API versions at the same time. In order to streamline the docs structure, the necessary changes to do the same in this repo are applied here as well.
refs fluxcd/website#1577

Align docs structure with other controllers

---

api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
docs/api/v2beta1/helm.md
docs/spec/v2beta1/helmreleases.md
internal/controller/helmrelease_controller.go
main.go

This adds a `--interval-jitter-percentage` flag to the controller to
add a +/- percentage jitter to the interval defined in a HelmRelease
(defaults to 5%).
Effectively, this results in a reconciliation every 9.5 - 10.5 minutes
for a resource with an interval of 10 minutes.
Main reason to add this change is to mitigate spikes in memory and
CPU usage caused by many resources being configured with the same
interval.
Part of: https://github.com/fluxcd/flux2/issues/4120

controller: jitter requeue interval

---

go.mod
go.sum
internal/controller/helmrelease_controller.go
main.go

~Depends on https://github.com/fluxcd/pkg/pull/612~
Use the metrics helper to record all the metrics. Metrics helper ensures that the metrics for deleted objects are deleted as well.
Move all the metrics recording to be performed at the very end of the reconciliation. Realtime metrics for readiness is no longer recorded as it will be removed in a future version for CRD metrics collected using kube-state-metrics. Updating the object status with realtime readiness should provide the readiness to CRD metrics watchers.
`HelmReleaseReconciler.reconcileDelete()` is modified to receive a pointer HelmRelease object so that any modifications on the object is reflected on the object instance that's passed to the metrics recorder. This is not needed for `HelmReleaseReconciler.reconcile()` as it …

Delete stale metrics on object delete

---

internal/controller/helmrelease_controller_chart.go

This pull request adds a check for nil artifact when determining if the source chart is ready.
A recovered nil panic was reported on Slack.
https://cloud-native.slack.com/archives/CLAJ40HV3/p1694379977158039?thread_ts=1694280268.559579&cid=CLAJ40HV3
> {"level":"error","ts":"2023-09-08T18:12:10.583Z","logger":"runtime","msg":"Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)\ngoroutine 118 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x1ddc280?, 0x342b2c0})\n\tk8s.io/apimachinery@v0.27.4/pkg/util/runtime/runtime.go:75 +0x99\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()\n\tsigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go: …

Check source for nil artifact before loading chart

---

internal/controller/helmrelease_controller.go
internal/runner/runner.go

runner: address regression in captured Helm logs

---

internal/controller/helmrelease_controller.go

This addresses an issue in which the defunct `DefaultServiceAccount` from the `HelmReleaseReconciler` was being used to construct the impersonator used by the differ.
Fixes: #772

controller: use `DefaultServiceAccount` in differ

---

internal/controller/helmrelease_controller.go

When charts are not available in SC storage (e.g. after a Flux upgrade) all releases fail to reconcile with `HelmChart is not ready` and HR status is set to `Ready=False`. The controller would not retry the reconciliation when the chart artifact become available in storage, instead  the controller is using the `.spec.interval` for retries which forces users to set low intervals just to cope with upgrades. This PR changes the chart watcher to trigger a reconciliation for failed releases the moment charts become ready.

fix: Retry failed releases when charts are available in storage

---

internal/digest/digest.go
internal/digest/digest_test.go
main.go

This introduces a `--snapshot-digest-algo` flag to allow configuring a different algorithm than SHA256.
This allows the user to for example configure `blake3`, which is potentially faster (and less resource intensive) on modern hardware.

Allow configuration of snapshot digest algorithm

---

api/v2beta1/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml

Part of: https://github.com/fluxcd/flux2/issues/4410

Add deprecation warning to v2beta1 API

---

go.mod
go.sum
internal/action/diff.go
internal/action/diff_test.go
internal/diff/summarize.go
internal/diff/summarize_test.go
internal/reconcile/atomic_release.go
internal/reconcile/atomic_release_test.go
internal/reconcile/correct_cluster_drift.go
internal/reconcile/correct_cluster_drift_test.go
internal/reconcile/reconcile.go
internal/reconcile/release_test.go
internal/reconcile/state_test.go

This changes the cluster drift correction behavior from performing a
Helm upgrade to performing create and patch API requests based on the
JSON Patch data.
Doing this is much lighter than performing a full release cycle, and
deals with the issue of Helm being unable to restore state of Custom
Resources without the `--force` flag being set. Which has unwanted
side-effects like forcing objects through a deletion/creation cycle.
After a drift correction attempt a Kubernetes Event is emitted, which
contains a summary of the created and patched resources, and a
collection of any (potential) errors.
As the goal is to restore state as best as we can, the drift correction
will be re-attempted until all resources have been restored to the
desired state.
Fixes #805

Correct cluster drift using patches

---

api/v2beta2/annotations.go
api/v2beta2/annotations_test.go
api/v2beta2/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
docs/api/v2beta2/helm.md
internal/action/reset.go
internal/action/reset_test.go
internal/controller/helmrelease_controller.go
internal/reconcile/atomic_release.go
internal/reconcile/atomic_release_test.go

Implementation of https://github.com/fluxcd/helm-controller/issues/366#issuecomment-980180263
This introduces two new annotations:
- `reconcile.fluxcd.io/resetAt`: to reset the failure counts for a
`HelmRelease` object.
- `reconcile.fluxcd.io/forceAt`: to allow a one-off Helm install or
upgrade when the controller would otherwise do nothing (e.g. due to
being out of retries, in-sync, in a failed state, etc.)
Both annotations require the `reconcile.fluxcd.io/requestedAt`
annotation to be set at the same time, with the same token value.
```sh
TOKEN="$(date +%s)"; \
kubectl annotate --field-manager=flux-client-side-apply --overwrite helmrelease/<name> \
"reconcile.fluxcd.io/requestedAt=$TOKEN" \
"reconcile.fluxcd.io/forceAt=$TOKEN"
```
Fixes #267
Fixes #366 
Fixes #454
Fixes #297

Introduce `forceAt` and `resetAt` annotations

---

internal/reconcile/helmchart_template.go

Due to the frequency, this would otherwise suppress other Kubernetes Events which are more important. Especially when the `.spec.interval` of the HelmRelease is set to a low value.

reconcile: do not emit HelmChartInSync event

---

internal/reconcile/install.go
internal/reconcile/install_test.go
internal/reconcile/upgrade.go
internal/reconcile/upgrade_test.go

When a Helm install or upgrade is performed, to prevent confusion due to reporting a stale test result.

reconcile: remove stale `TestSuccess` condition

---

api/v2beta2/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
docs/api/v2beta2/helm.md

They have been deprecated for a long time, and should be scheduled for removal to ensure they can be removed in the final `v2` release.
xref: https://github.com/fluxcd/helm-controller/pull/828#discussion_r1417265898

api: deprecate stragic merge and JSON 6902 patches

---

.github/workflows/e2e.yaml

This test has shown to be a flake on multiple ocassions.
After running it locally a dozen of times, my conclusion is that the
time it takes for Kubernetes to shutdown a Pod may sometimes be a tiny
bit longer than anticipated by the current timeout.
Therefore, increase it to 5 minutes and provide more context on the
state of the namespace in case a timeout occurs.

ci: increase timeout delete-ns tests

---

internal/controller/helmrelease_controller_test.go

As the Kubernetes client used in tests is cache backed, it can take a tiny bit of time for the client to actually notice the removal.
Wrapping in `Eventually` should address this.
As observed in https://github.com/fluxcd/helm-controller/actions/runs/7169853780/job/19521199735

controller: address test flake

---

README.md
docs/spec/README.md
docs/spec/v2beta2/README.md
docs/spec/v2beta2/helmreleases.md

Would be nice to add (but could be added later):

docs/spec: document `v2beta2` API

---

docs/spec/v2beta2/helmreleases.md

There must be at least one other, but I cannot find it again.

docs/spec: address typo

---

internal/loader/artifact_url.go
internal/loader/artifact_url_test.go

This adds back the support for overwriting the host name a chart is downloaded from (again) using the `SOURCE_CONTROLLER_LOCALHOST` environment variable.

loader: allow overwrite of URL hostname again

---

internal/controller/helmrelease_controller.go
internal/controller/helmrelease_controller_test.go
internal/loader/client.go

Part of: https://github.com/fluxcd/flux2/issues/4472

loader: log HTTP errors to provide faster feedback

---

internal/reconcile/atomic_release.go
internal/reconcile/atomic_release_test.go

Detect stall condition due to exhausted remediation retry right after remediating. This helps return from the AtomicRelease.Reconcile() with proper stalled status condition and error. Without this, after remediation, especially during upgrade failures, a stalled condition detection required a new reconciliation, leaving the status of the object without any Reconciling or Stalled condition.

Early stall condition detection after remediation

---

api/v2beta1/helmrelease_types.go
api/v2beta1/zz_generated.deepcopy.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml

As we are (still) not making use of conversion webhooks, new fields can only be introduced by including them in all served API versions. As otherwise conversion will fail.
Fix: https://github.com/fluxcd/flux2/issues/4479

api: ensure backwards compatibility v2beta1

---

CHANGELOG.md
config/manager/kustomization.yaml
go.mod

Part of: https://github.com/fluxcd/flux2/issues/4473

Release v0.37.1

---

main.go

This accidentally did not get `if`-wrapped in
eaa2a8c2fe78e3b7d5aa9fcedc7757b3c4005f51, breaking the configuration option to watch a single namespace, and thereby as by-effect the breakage of sharding.
Fixes https://github.com/fluxcd/flux2/issues/4500

Properly configure namespace selector

---

api/v2beta1/helmrelease_types.go
api/v2beta2/helmrelease_types.go

This tag isn't used by controller-tools, only `nonNamespaced` is.
Context: https://cloud-native.slack.com/archives/CLAJ40HV3/p1708794732147909
Tested by running `make generate` and verifying that there is no diff.

Remove `genclient:Namespaced` tag

---

internal/controller/helmrelease_controller.go

This is a follow up to https://github.com/fluxcd/helm-controller/pull/907 that used the wrong event types.

Use corev1 event type for sending events

---

internal/reconcile/atomic_release.go

fix #925 
Make sure that `/data` for configmaps are not masked

Fix patching on drift detection

---

.github/workflows/e2e.yaml
api/v2beta2/reference_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
config/testdata/install-from-hc-source/test.yaml
docs/spec/v2beta2/helmreleases.md
internal/controller/helmrelease_controller_test.go

If implemented, user will be able to share an existing HelmChart custom resource between HelmReleases.
Closes: https://github.com/fluxcd/helm-controller/issues/204
Followup: #905

Add support for `HelmChart` as chartRef

---

internal/reconcile/correct_cluster_drift.go
internal/reconcile/correct_cluster_drift_test.go

Related to the issue described in https://github.com/fluxcd/flux2/issues/4524 and observations from https://github.com/fluxcd/helm-controller/issues/855. And another instance of the issue discussed on slack that revealed that stale Ready=False value results in such scenarios (described in #884 and more below).
This change builds on top of https://github.com/fluxcd/helm-controller/pull/884, to solve the issue at different levels. Please read #884 for more details about the issue.
Update the Ready condition during drift correction to reflect the current state of reconciliation. Without this, any previous Ready condition value continues to persist on the object. If there was a previous failure due to which Ready=False condition is present on the object, the same value continues to persist if …

Update Ready condition during drift correction

---

api/v2/snapshot_types.go
api/v2beta1/helmrelease_types.go
api/v2beta1/zz_generated.deepcopy.go
api/v2beta2/helmrelease_types.go
api/v2beta2/zz_generated.deepcopy.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
docs/api/v2/helm.md
docs/spec/v2/helmreleases.md
internal/reconcile/correct_cluster_drift.go
internal/reconcile/install.go
internal/reconcile/install_test.go
internal/reconcile/release.go
internal/reconcile/rollback_remediation.go
internal/reconcile/rollback_remediation_test.go
internal/reconcile/test.go
internal/reconcile/test_test.go
internal/reconcile/uninstall.go
internal/reconcile/uninstall_remediation.go
internal/reconcile/uninstall_remediation_test.go
internal/reconcile/uninstall_test.go
internal/reconcile/unlock.go
internal/reconcile/unlock_test.go
internal/reconcile/upgrade.go
internal/reconcile/upgrade_test.go
internal/release/observation.go
internal/testutil/mock_chart.go

This PR adds the chart app version to the `.status.history` snapshot and sets the `app-version` annotation to all the issued events. 
This PR makes possible to expose `chart_app_version` as a label on the `gotk_resource_info` metric, ref: https://github.com/fluxcd/flux2-monitoring-example/pull/36

Add the chart app version to status and events metadata

---

api/v2/helmrelease_types.go
api/v2beta1/helmrelease_types.go
api/v2beta2/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
docs/api/v2/helm.md
docs/spec/v2/helmreleases.md
internal/controller/helmrelease_controller.go
internal/controller/helmrelease_controller_test.go
internal/postrender/build.go
internal/reconcile/reconcile.go
internal/reconcile/release.go
internal/reconcile/release_test.go
internal/reconcile/state.go
internal/reconcile/state_test.go

Track changes in `.spec.postRenderers`

---

internal/release/digest_test.go
internal/release/observation.go

Mark `Observation.OCIDigest` as `omitempty` to avoid a snapshot drift when upgrading to API v2.
Before this fix, when updating the controller & CRDs from v0.x to v1.0 all releases were upgraded due to:
```
release not managed by controller: release not observed to be made for object
```
Whit this fix, the history snapshot remains unchanged, as the OCI digest empty string is no longer included in the calculation of the config digest.
Followup: https://github.com/fluxcd/helm-controller/pull/905

Prevent snapshot drift when upgrading to API v2

---

.goreleaser.yaml
CHANGELOG.md
config/manager/kustomization.yaml
go.mod

🎉  This is the general availability release of helm-controller and `HelmRelease` v2 API.
Part of: https://github.com/fluxcd/flux2/issues/4712

Release v1.0.0

---

docs/spec/v2/helmreleases.md
docs/spec/v2beta2/helmreleases.md

In the HelmRelease documentation, the default value for `.spec.upgrade.crds` is set as `None` in [Upgrade configuration](https://fluxcd.io/flux/components/helm/helmreleases/#upgrade-configuration) part, then the default value is set as `Skip` in [Controlling the lifecycle of Custom Resource Definitions](https://fluxcd.io/flux/components/helm/helmreleases/#controlling-the-lifecycle-of-custom-resource-definitions) part.

doc: fix HelmRelease default value for `.spec.upgrade.crds`

---

internal/controller/helmrelease_controller.go
internal/controller/helmrelease_controller_test.go

Tools such as Bitnami's charts-syncer strip the `v` prefix from the chart version so that the OCI artifact version differs from the version defined in the chart's metadata. This leads to an error similar to this returned from h-c:
```
artifact revision 1.14.5 does not match chart version v1.14.5
```
This PR makes h-c ignore a leading `v` prefix in either the chart version of the OCI artifact tag.

Ignore 'v' version prefix in OCI artifact and Helm chart

---

internal/reconcile/atomic_release.go

fix #1008 
We previously disabled logging json patches on `ReleaseStatusDrifted` due to the fact that the `MaskSecretPatchData()` cannot differentiate between `Secrets` and `ConfigMaps` in #935
We are re-enabling this with a check on the `kind` to know when to call `MaskSecretPatchData()`.

Re-enable logging json patch on StatusDrifted

---

internal/controller/helmrelease_controller.go
internal/reconcile/atomic_release.go
internal/reconcile/install.go
internal/reconcile/rollback_remediation.go
internal/reconcile/test.go
internal/reconcile/uninstall.go
internal/reconcile/uninstall_remediation.go
internal/reconcile/unlock.go
internal/reconcile/upgrade.go

The `Mark…` functions in the `conditions` package accept a format string and (optional) arguments, just like `fmt.Printf` and friends.
In many places, the code passed an error message as the format string, causing it to be interpreted as a format string by the `fmt` package. This leads to issues when the message contains percent signs, e.g. URL-encoded values.
This PR adds a format string and shortens `err.Error()` to `err`, which yields the same output.
This change is identical in principle to fluxcd/source-controller#1529.

Fix incorrect use of format strings with the `conditions` package.

---

docs/spec/v2/helmreleases.md
docs/spec/v2beta2/helmreleases.md
internal/chartutil/values.go
internal/chartutil/values_test.go

Fix: https://github.com/fluxcd/flux2/issues/2330
When using Helm with both a values file and --set, the set will always have precedence over the values.yaml. This allows specifying the normal config inside a yaml file and specifying a secret outside that yaml via --set.
When using flux, this normally works too (using inline values to specify most of the config and a reference with targetPath to get a secret), but if you want to overwrite a secret key inside an array the inline values will always overwrite the whole array and the referenced secret key will not appear at all.
By making sure that when you specify a targetPath it has precedence over inline values it will be merged properly.
The Workaround mentioned in the original issue is limiting, because you can not easily use kustomize to …

Allow overwriting inline values with targetPath

---

docs/spec/v2/helmreleases.md
internal/controller/helmrelease_controller_test.go
internal/reconcile/uninstall.go
internal/reconcile/uninstall_test.go

fix: remove digest check to never ignore helm errors

---

api/v2/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
docs/api/v2/helm.md
docs/spec/v2/helmreleases.md
internal/action/install.go
internal/action/upgrade.go

This PR adds a new field called `disableSchemaValidation` to both `.spec.install` and `.spec.upgrade` that allows disabling the values validation against the JSON schema during install and upgrade. 
Closes: https://github.com/fluxcd/flux2/issues/4992
xref: https://github.com/helm/helm/pull/12743

Add `disableSchemaValidation` to Helm install/upgrade actions

---

internal/controller/helmrelease_controller.go
internal/controller/helmrelease_controller_test.go
main.go

Use the `APIReader` client to bypass the controller runtime cache when checking for dependencies. This allows a HelmRelease to depend on other HelmReleases managed by different controller shards.
xref: https://github.com/fluxcd/kustomize-controller/pull/1248

Allow cross-shard dependency check

---

internal/controller/helmrelease_controller.go
internal/controller/helmrelease_controller_test.go

Closes https://github.com/fluxcd/helm-controller/issues/1099
OCI tags are not semver compatible, with `+` character not allowed. Helm worked around this by converting `+` to `_` before pushing to the OCI repo and vice versa when pulling from the repo.
This PR makes helm-controller adhere to that convention, by converting OCI artifact tag using `_` to `+` replacement prior to any check or processing.

Replace `_` with `+` when verifying the chart version matches the OCI artifact tag

---

docs/spec/v2/helmreleases.md

Document the usage of `flux debug hr` in the API docs.
Part of: https://github.com/fluxcd/flux2/issues/5101

docs: Rendering the final Values locally

---

api/v2/helmrelease_types.go

Add `ValuesReference` as an alias to `meta.ValuesReference` to avoid breaking changes to the Go HelmRelease v2 API.

Make `ValuesReference` an alias for backwards compat

---

api/v2/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
docs/api/v2/helm.md
docs/spec/v2/helmreleases.md
internal/action/install.go
internal/action/install_test.go
internal/action/upgrade.go
internal/action/upgrade_test.go

This change adds a new field called `disableTakeOwnership` to `.spec.install` and `.spec.upgrade`. The flag allows users to disable ignoring helm annotations and labels before taking ownership of existing resources during install and upgrade.
Closes https://github.com/fluxcd/helm-controller/issues/1139
xref: https://github.com/helm/helm/pull/13439

Add `disableTakeOwnership` to Helm install/upgrade actions

---

internal/action/crds.go
internal/action/install.go
internal/action/upgrade.go
internal/reconcile/install_test.go
internal/reconcile/upgrade_test.go
internal/testutil/mock_chart.go

Fix install and upgrade applying subchart CRDs when condition is false

---

internal/action/rollback.go
internal/action/rollback_test.go

Without this fix, HelmRelease stuck in infinite rollback remediation loop could create lots of revisions and Secrets for them, which can cause k8s control plane to be unresponsive or other components loading Secrets to crash OOM.
Infinite rollback remediation loop can happen e.g. in case both HelmRelease upgrade and rollback depend on a mutating or validating webhook availability and HelmRelease is configured with infinite rollback remediation, so failed upgrade triggers rollback remediation which can't succeed too and keeps on being retried, generating revision in every retry.

fix: use HelmRelease max history for rollback remediation

---

internal/kube/roundtripper.go

fix the wrong error return value

fix: fix the wrong error return value

---

docs/spec/v2/helmreleases.md
internal/controller/helmrelease_controller.go
internal/controller/helmrelease_controller_test.go
internal/features/features.go
main.go

Fix: https://github.com/fluxcd/flux2/issues/4910
When using `OCIRepository` for Helm charts that set the chart version as a label e.g. `app.kubernetes.io/version: {{ .Chart.Version }}`, helm-controller will fail to install the Helm release due to appending the digest to the chart version:
```
Helm upgrade failed  invalid: spec.template.labels: Invalid value: "0.9.3+4fda46fd8c4e": a valid label must be an empty string or consist of alphanumeric characters
```
This PR makes it possible to disable the chart digest tracking at controller level. When the feature gate is enabled, Flux will no longer trigger a Helm release upgrade if the digest changed unless the chart version changes too.
To deploy the release candidate and test the `DisableChartDigestTracking` feature gate, add the following …

Add `DisableChartDigestTracking` feature gate

---

api/v2/helmrelease_types.go
api/v2beta1/helmrelease_types.go
api/v2beta2/helmrelease_types.go
config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
docs/api/v2/helm.md

As described at https://go.dev/wiki/Deprecated, the `Deprecated` comments shall start a new paragraph. This way, the deprecation is also visible to other tools like staticcheck or vscode. Otherwise, one might get surprised by the removal of deprecated fields.
I also ran `make manifests`, which adds some newlines.

Move 'Deprecated' comments to own paragraph

---

internal/controller/helmrelease_controller.go

There could be an `OCIRepository` and a `HelmChart` with the same `{namespace}/{name}`, so the watch index should make a distinction using the kind.
Also fixing a typo `requestsForOCIRrepositoryChange` -> `requestsForOCIRepositoryChange`.

Fix watch index conflict between HelmChart and OCIRepository kinds

---

internal/controller/helmrelease_controller.go
internal/controller/helmrelease_controller_test.go

We found out that if the Kubernetes API is overwhelmed some watch events may be missed during bootstrap scenarios. We are fixing the requeue behavior here to match kustomize-controller, it uses the `--requeue-dependency` flag to control the duration of this requeue interval.

Fix requeue interval for SourceNotReady
