fluxcd/helm-controller

api/v2alpha1/helmrelease_types.go, config/crd/bases/helm.fluxcd.io_helmreleases.yaml
* add 'ready', 'status' and 'age' columns to CRD
* add 'hr' as shortname for HelmReleases
=> CRD tweaks

controllers/helmrelease_controller.go
Fixes #8, also includes https://github.com/fluxcd/toolkit/issues/94.
=> Broadcast events for Helm actions

api/v2alpha1/helmrelease_types.go, config/crd/bases/helm.fluxcd.io_helmreleases.yaml, controllers/helmrelease_controller.go, controllers/helmrelease_predicate.go, docs/api/helmrelease.md
Ref: https://github.com/fluxcd/toolkit/issues/89
=> Refactor garbage collection to finalizer

api/v2alpha1/helmrelease_types.go, controllers/helmrelease_controller.go
- helm action result handling
- common fields set after release attempt (success or fail)
=> Factor out common patterns

controllers/helmrelease_controller.go
=> Fix: use fetched HelmChart object for update

controllers/helmrelease_controller.go
=> Fix: use composed release name in Helm actions

controllers/helmrelease_controller.go
=> Reevaluate ready status after transient errors

api/v2alpha1/condition_types.go, controllers/helmrelease_controller.go
Ref: https://github.com/fluxcd/toolkit/issues/125
=> Take observed generation of dependencies into account

controllers/helmrelease_controller.go
After taking a closer look at the Helm code, this is the behaviour
we are actually after, given we want to mimic the merging behaviour
of the -f flag available to Helm install and/or upgrade commands.
=> Allow overwrites of map values with flat values

Makefile
=> Make various make targets work after api pkg change

.github/workflows/e2e.yaml, Makefile, api/v2alpha1/reference_types.go, config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml, config/testdata/valuesfrom/configmap.yaml, config/testdata/valuesfrom/golden.txt, config/testdata/valuesfrom/helmrelease.yaml, config/testdata/valuesfrom/secret.yaml, controllers/helmrelease_controller.go, docs/api/helmrelease.md, docs/spec/v2alpha1/helmreleases.md
=> Support targeting a path in ValuesReferences

config/manager/kustomization.yaml
=> Update image tag to v0.0.5

api/v2alpha1/helmrelease_types.go, config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml, config/default/kustomization.yaml, controllers/helmrelease_controller.go, docs/api/helmrelease.md, go.mod, go.sum
=> Support HelmChart ValuesFile field

go.mod, go.sum
* helm.sh/helm/v3 to v3.3.4
* github.com/fluxcd/source-controller/api to v0.0.18
=> Upgrade Helm and source-controller dependencies

Dockerfile, controllers/helmrelease_controller.go, go.mod, go.sum, internal/runner/runner.go, internal/util/util.go, internal/util/util_test.go
Goal of this PR is to factor out logical bits of the controller into packages, to increase code readability and improve testing capabilities.
=> Factor out bits and pieces of controller

docs/spec/v2alpha1/helmreleases.md
=> Remove leftover `lastObservedTime` references

.github/workflows/e2e.yaml, config/testdata/targetnamespace/helmrelease.yaml, controllers/helmrelease_controller.go, internal/runner/runner.go
=> Configure release namespace in runner constructor

.github/workflows/e2e.yaml, .github/workflows/fossa.yml, .github/workflows/release.yml, README.md, docs/internal/release.md, docs/spec/v2alpha1/helmreleases.md, docs/spec/v2beta1/helmreleases.md
Ref: https://github.com/fluxcd/toolkit/issues/152
=> Set default branch to main

docs/spec/v2beta1/helmreleases.md
Ref: https://github.com/fluxcd/toolkit/issues/319
=> Add namespace to API docs examples

controllers/helmrelease_controller.go
By confirming the observed generation is up-to-date before checking
the `Ready` condition state after chart reconciliation, we guarantee
the chart we use for the release always is on par with the state of
the `HelmRelease`.
In addition, we requeue to prevent the `HelmRelease` getting stuck
in a "HelmChart is not ready" state. Previously triggered by a no-op
chart update without a revision change that caused the watcher to
not request a reconciliation for the `HelmRelease`.
Ref: #112
=> Change chart reconciliation and readiness logic 

docs/spec/v2alpha1/helmreleases.md, docs/spec/v2beta1/helmreleases.md
=> Fixing typo (issue #118)

CHANGELOG.md, config/default/kustomization.yaml, config/manager/kustomization.yaml, docs/spec/v2beta1/helmreleases.md, go.mod, go.sum
Ref: https://github.com/fluxcd/toolkit/issues/388
=> Release v0.2.0

docs/spec/v2beta1/helmreleases.md
=> Add the impersonation feature to API spec

.github/workflows/e2e.yaml, api/v2beta1/helmrelease_types.go, config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml, config/testdata/impersonation/test.yaml, controllers/helmrelease_controller.go, docs/api/helmrelease.md
This PR implements the spec from #155
Fix: #154
=> Implement service account impersonation

Makefile, api/go.mod, api/go.sum, config/manager/deployment.yaml, go.mod, go.sum, main.go
Add readiness/liveness probes using controller-runtime helpers.
=> Add readiness/liveness probes

controllers/helmrelease_controller.go
This prevents the resource hanging forever if the release does not exist
in the Helm storage because it was either never created, or because it
was already removed by e.g. Kubernetes due to a namespace deletion.
=> Ignore missing release on HR delete

docs/spec/v2beta1/helmreleases.md
=> docs Update helmreleases.md dependsOn

Dockerfile
Changes:
- Update Alpine to 3.13
- Fix controller group assignment
=> Update Alpine to v3.13

config/default/kustomization.yaml
=> Use source-controller manifest from GitHub release

controllers/helmrelease_controller.go
Reverts fluxcd/helm-controller#234
=> Revert "Record suspend metrics"

api/go.mod, api/go.sum, go.mod, go.sum
Followup: https://github.com/fluxcd/pkg/pull/96
Fix: #247
=> Update fluxcd/pkg/runtime to v0.10.2

.github/workflows/e2e.yaml, .github/workflows/nightly.yaml, .github/workflows/release.yml
Changes to CI:
- Add nightly builds workflow
- Allow publishing release candidate images
=> Add nightly builds workflow and allow RC releases

Makefile
Signed-off-by: Sanskar Jaiswal <sanskar.jaiswal@weave.works>
Ref: https://github.com/fluxcd/flux2/issues/2273
=> Use go-install-tool for gen-crd-api-reference-docs

controllers/helmrelease_controller.go
Following example of fluxcd/source-controller#542
=> Use patch instead of update when adding finalizers

.github/workflows/cifuzz.yaml, .github/workflows/e2e.yaml, .github/workflows/nightly.yaml, .github/workflows/release.yml, .github/workflows/scan.yaml, .goreleaser.yaml
This PR implements:
- https://github.com/fluxcd/flux2/issues/2302
- https://github.com/fluxcd/flux2/issues/2303
=> Publish SBOM and sign release artifacts

docs/spec/v2beta1/helmreleases.md
Fixes #430 
Fixes https://github.com/fluxcd/website/issues/819.
=> Update links to kubectl documentation

go.mod, go.sum
Ref: https://github.com/fluxcd/flux2/issues/2574
=> Update Kustomize to v4.5.3

README.md
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> update docs links to toolkit.fluxcd.io

controllers/helmrelease_controller.go
Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>
Implements RecoverPanic option on reconciler.
part of [issue #2952](https://github.com/fluxcd/flux2/issues/2952#issue-1325576799)
=> Enable RecoverPanic option on reconciler

DEVELOPMENT.md, README.md
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> update to new doc links structure

MAINTAINERS
cc @seaneagan 
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> Update MAINTAINERS info

docs/spec/v2alpha1/helmreleases.md, docs/spec/v2beta1/helmreleases.md
Signed-off-by: Fred Rolland <frolland@nvidia.com>
=> Minor typo in doc

internal/runner/runner.go
=> assign the value of 'DisableOpenApiValidation' from the HelmRelease

.github/workflows/scan.yaml
Same as https://github.com/fluxcd/flux2/pull/3601
=> ci: Fix Snyk code scanning

.github/workflows/nightly.yaml, .github/workflows/release.yml, .github/workflows/scan.yaml
Part of https://github.com/fluxcd/flux2/issues/3663
=> build: update release workflow

.goreleaser.yaml, config/default/kustomization.yaml, go.mod, go.sum
=> Update source-controller to v0.36.0

internal/controllers/helmrelease_controller.go
Hotfix to deal with the issue, as we will soon be moving to the patch logic used by already rewritten controllers. This is however a pain for many users, so worth solving now.
Fixes #571
Fixes #258
=> controllers: update status patch logic

internal/controllers/helmrelease_controller.go
=> Fix nil pointer deref during diff attempt

internal/controller/helmrelease_controller.go
Supersedes #681
Implementation of https://github.com/fluxcd/pkg/pull/544 in combination with https://github.com/fluxcd/notification-controller/pull/530
Fixes https://github.com/fluxcd/helm-controller/issues/678
=> Use last attempted values checksum as event metadata token

internal/controller/helmrelease_controller.go
Follow up #692, fixes https://github.com/fluxcd/flux2/issues/3937
=> Include revision and token in event metadata

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
First release with SLSA level 3 provenance.
=> Release v0.34.2

.github/workflows/scan.yaml
To align with other controller projects.
=> scan: disable Snyk

DEVELOPMENT.md, api/go.mod, go.mod, tests/fuzz/Dockerfile.builder
Part of: https://github.com/fluxcd/flux2/issues/4014
=> Align `go.mod` version with Kubernetes (Go 1.20)

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Part of https://github.com/fluxcd/flux2/issues/4013
=> Release v0.35.0

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Part of: https://github.com/fluxcd/flux2/issues/4125
=> Release v0.36.0

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Part of: https://github.com/fluxcd/flux2/issues/4248
=> Release v0.36.1

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Part of https://github.com/fluxcd/flux2/issues/4309
=> Release v0.36.2

config/default/kustomization.yaml, go.mod, go.sum
Update source-controller yamls to last version.
=> Update source-controller to v1.1.2

config/testdata/charts/crds/bootstrap/templates/git-repository.yaml, internal/action/upgrade.go, internal/controller/helmrelease_controller_fuzz_test.go
Hidden surprises found when merging #738 into `main`.
=> Address minor issues

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Part of: https://github.com/fluxcd/flux2/issues/4410
=> Release v0.37.0

api/v2beta2/helmrelease_types.go, config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
Followup: https://github.com/fluxcd/source-controller/pull/1075
=> Add `notation` verification provider to API

.github/labels.yaml
Part of https://github.com/fluxcd/flux2/issues/5186
=> Add 1.2.x release label

.github/labels.yaml
Part of: https://github.com/fluxcd/flux2/issues/5363
=> Add 1.3.x release label

go.mod, go.sum
Depends on: https://github.com/fluxcd/pkg/pull/988
Part of: https://github.com/fluxcd/flux2/issues/5022
=> [RFC-0010] Support all Azure clouds for remote clusters at the controller level

go.mod, go.sum, main.go
ref: https://github.com/fluxcd/source-controller/pull/1872#discussion_r2280877451
follow-up: #1284
=> Add object-level configuration validation
